sonar.projectKey=skainet-api
sonar.projectName=Skainet API
sonar.sourceEncoding=UTF-8
sonar.sources=Skainet-API/src
sonar.tests=Skainet-API/src,Skainet-API/pruebas,test/unitarias,test/integracion
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=Skainet-API/coverage/lcov.info
